### PR TITLE
Set VisibilityTimeout based on _peekLockDuration

### PR DESCRIPTION
**Pull request by micdah**
To ensure the newly created SQS queue has the same visibility timeout as our peeklock task expects (based on _peekLockDuration), we set the 'VisibilityTimeout' attribute on the SQS queue to the same value.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by micdah** [comment]
Looks like the issue relates to when a queue already exists, with the same name but different settings, then Amazon SQS returns a HTTP-400 complaining about this.

I suspect we could circumvent this by splitting it into two separate operations, checking if the queue already exists and if so, update attributes - otherwise create with desired VisibilityTimeout

**Comment by mookid8000** [comment]
Super! BRB

**Comment by mookid8000** [comment]
It's out in 4.0.0-b11 in a few seconds 😄 

Thanks for correcting this 👍

**Comment by micdah** [comment]
Awesomesauce! 😄

**Pull request merged**
