### PR TITLE
Support MessageGroupId and MessageDeduplicationId parameters

### PR DESCRIPTION
**Pull request by knepe**
Should fix https://github.com/rebus-org/Rebus.AmazonSQS/issues/24

### CODE REVIEW

**Comment by mookid8000** [comment]
Cool 👍 if you click the CLA thing above and sign it, then I can accept your PR

**Comment by knepe** [comment]
@mookid8000 Maybe we should check if the queue is really a FIFO queue before adding the `MessageGroupId` and `MessageDeduplicationId`? According to the documentation it should only be used on FIFO queues. Does the `Address` property  contain the queue name? If so, we can just add `Address.EndsWith(".fifo")` because all FIFO queues must have .fifo suffix

**Comment by knepe** [comment]
Sorry, my last commits seem to break some test, unfortunately I can't run the tests on my computer for some reason.. Do you know what could be breaking it in AppVeyor? The test is `Rebus.AmazonSQS.Tests.AmazonSqsSimpleSend.HasOneWayClient` and the error is `Object reference not set to an instance of an object.
   at Rebus.AmazonSQS.AmazonSqsTransport.<SendOutgoingMessages>b__21_2(OutgoingMessage message) in C:\projects\rebus-amazonsqs\Rebus.AmazonSQS\AmazonSQS\AmazonSqsTransport.cs:line 283`
That line is this if I'm not mistaken: https://github.com/knepe/Rebus.AmazonSQS/commit/0af2d767f548ad2b4c27bfe34fd2b0edaa5eeabe#diff-dcfd14ea4d73a88554b596597e107a95R283

**Comment by mookid8000** [comment]
> Maybe we should check if the queue is really a FIFO queue before adding the MessageGroupId and MessageDeduplicationId? According to the documentation it should only be used on FIFO queues. 

Does that mean that it is an error to add the message group ID and message dedupe ID on a queue entry if the destination queue is not a FIFO queue?

> Does the Address property contain the queue name? If so, we can just add Address.EndsWith(".fifo") because all FIFO queues must have .fifo suffix

`Address` has the INPUT queue address, but in this case it's the destination queue we care about. This probably explains why you get a `NullReferenceException` somewhere in a one-way client, because  the `Address` property of one-way clients returns `null`.

**Comment by knepe** [comment]
I'm not sure if the request will fail if passing MessageGroupId to a non fifo queue, but documentation says this : "MessageGroupId is required for FIFO queues. You can't use it for Standard queues.". It might be that the request will work anyway and if so maybe the checking if it's a fifo queue is not needed

**Comment by mookid8000** [comment]
cool thanks 👍 it'll be out in 5.0.0-b03 in a few minutes

**Pull request merged**
